---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta1","kind":"GitRepository","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"gitImplementation":"libgit2","interval":"1m0s","ref":{"branch":"prd"},"secretRef":{"name":"flux-system"},"url":"https://sakuh@bitbucket.org/sakuh/flux-cd-repo.git"}}
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m0s
  ref:
    branch: prd
  secretRef:
    name: flux-system
  timeout: 20s
  url: https://sakuh@bitbucket.org/sakuh/flux-cd-repo.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta2","kind":"Kustomization","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"10m0s","path":"./clusters/my-cluster","prune":true,"sourceRef":{"kind":"GitRepository","name":"flux-system"}}}
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

